### ISSUE TITLE
Diacritics should be considered

### ISSUE THREAD

**Issue by batcaverna** [TarekRaafat/autoComplete.js#77] opened 2019-09-24 21:11 UTC
Greetings,

Is there a way to use **localeCompare** instead of **match** in order to include accented characters into the search?

**Comment by batcaverna** [comment] 2019-09-24 22:12
Answering my own question: Tried this, seems to work fine.

217c217
<             if (searchPosition < query.length && String(recordLowerCase[number]).localeCompare(query[searchPosition], 'pt', {sensitivity: 'base'}) == 0) {
---
>             if (searchPosition < query.length && recordLowerCase[number] === query[searchPosition]) {
228,230c228
<           let r = recordLowerCase.normalize("NFD").replace(/[\u0300-\u036f]/g, ""),
<               q = query.normalize("NFD").replace(/[\u0300-\u036f]/g, "");
<           if (r.includes(q)) {
---
>           if (recordLowerCase.includes(query)) {

**Comment by TarekRaafat** [comment] 2019-09-25 18:55
Hello @batcaverna,

Thanks for your enhancement suggestion, can you please explain to us the underlying business use case you had with example and explain your solution to it more clearly?

Thanks again, have a nice day! :)

**Comment by braco** [comment] 2019-10-28 00:23
@TarekRaafat presumably to match foo to foô, etc.

**Comment by TarekRaafat** [comment] 2020-01-22 16:38
@braco , "Diacritics" support will be included in the coming update.

For the time being, you could use the `query` API as shown below for the results you're after.

```js
query: {
  manipulate: function (query) {
    return query.normalize("NFD").replace(/[\u0300-\u036f]/g, "");
  },
}
```

Try it and let me know how it worked with you.

**Comment by JavierMartinz** [comment] 2020-05-21 10:31
👋  Any news on this?

**Comment by TarekRaafat** [comment] 2020-05-22 09:34
Hello @JavierMartinz,

The development of the new version has been going on a slow pace recently due to the workload I'm having, and the fact that I'm the only one maintaining `autoComplete.js` so far. I've been considering smaller releases instead of fully-loaded ones but not decided yet.


Regarding your questions don't worry "Diacritics" support will be included within the coming release/releases but for now you could use the above-mentioned option until the release comes out.

```js
 query: {
  manipulate: function (query) {
    return query.normalize("NFD").replace(/[\u0300-\u036f]/g, "");
  },
}
```

Have a nice day, cheers! :)

**Comment by JavierMartinz** [comment] 2020-05-22 13:40
Hey @TarekRaafat, thanks for your reply.

I already tried that, the problem is that if the API returns an item with diacritics, lets say: `Mérida` (Spain city), Autocomplete.js will not detect it as a result.

**Comment by TarekRaafat** [comment] 2020-12-05 06:36
[v8.0](https://github.com/TarekRaafat/autoComplete.js/releases/tag/v8.0.0)

**Closed by TarekRaafat** 2020-12-05 06:36 UTC
Labels: enhancement
