### ISSUE TITLE
AutoComplete stops working (silently) after hard refresh or cache clear (webkit)

### ISSUE THREAD

**Issue by lougroshek** [TarekRaafat/autoComplete.js#155] opened 2020-12-10 22:00 UTC
## System information
- Safari 14
- Chrome 87
- MacOS 10.15.7
- Site is deployed on Netlify

## Error messages
The only error message in console indicates that livereload.js, requested by autoComplete.js, failed to load. This message is visible when autoComplete works and when it does not:

```
https://5fd294e3bc4a350007fa0e28--eviction-lab.netlify.app:35729/livereload.js?snipver=1 net::ERR_CONNECTION_REFUSED
(anonymous) @ autoComplete.js:2
(anonymous) @ autoComplete.js:2
```

## Description

[Load the page](https://5fd294e3bc4a350007fa0e28--eviction-lab.netlify.app/racial-and-gender-disparities-among-evicted-americans/) in Safari or Chrome on MacOS (iOS devices do not seem to reproduce it). Scroll down to the first chart, and use the search input above the chart. On first load, autoComplete works, suggesting county names as you type. If I do a hard refresh (CMD + R) or clear the cache, it autoComplete no longer works. There are no error messages. 

I cannot reproduce this locally, only when deployed.

## Workaround

The only thing that will resolve the issue is if I completely shut down the browser, start it up again, and reload the page.

## Expected behavior

autoComplete should work after hard refresh or clear cache.

## Screenshots

Before clear cache: 
<img width="1512" alt="Screen Shot 2020-12-10 at 3 59 58 PM" src="https://user-images.githubusercontent.com/746182/101835035-ca007b00-3b00-11eb-96ef-12b8b3711734.png">

After hard refresh (autoComplete still initialized, and clearly has data, but no errors):
<img width="1570" alt="Screen Shot 2020-12-10 at 4 00 54 PM" src="https://user-images.githubusercontent.com/746182/101835148-f6b49280-3b00-11eb-927f-5a0611b0a7c7.png">

After restart Chrome (works again):
<img width="1559" alt="Screen Shot 2020-12-10 at 4 04 19 PM" src="https://user-images.githubusercontent.com/746182/101835624-ab4eb400-3b01-11eb-8dc9-07881bdd233e.png">

Then clear cache (stops working):
<img width="1590" alt="Screen Shot 2020-12-10 at 4 04 46 PM" src="https://user-images.githubusercontent.com/746182/101835673-bc97c080-3b01-11eb-876b-0aae901165b0.png">
<img width="1610" alt="Screen Shot 2020-12-10 at 4 04 58 PM" src="https://user-images.githubusercontent.com/746182/101835680-c0c3de00-3b01-11eb-841a-471320f29d1e.png">

## Attempted solutions

- Disable data caching in autoComplete settings (no change)
- [Change to loading js locally](https://5fd2a101e4d62900071e98bb--eviction-lab.netlify.app/racial-and-gender-disparities-among-evicted-americans/) (no change)

**Comment by TarekRaafat** [comment] 2020-12-10 23:39
Hello @lougroshek,

Thank you for reporting this interesting issue I'm looking into it, and I'll get back to you asap.


Have a nice day, cheers!

**Comment by sellsteam13** [comment] 2020-12-11 00:35
+1. I have the same problem. Everything works OK in dev mode, but after project build autoComplete does not even initialize.
![dev](https://user-images.githubusercontent.com/60786111/101846303-550d5f80-3b59-11eb-817e-1c5a933993a9.png)
![build](https://user-images.githubusercontent.com/60786111/101846294-52ab0580-3b59-11eb-8ce0-3e997d677ad8.png)
link http://tsymbal01.beget.tech/dev/recomed/dist/page-main.html . Try to type 'google.com' in input.
Expected behavior:
![ggl](https://user-images.githubusercontent.com/60786111/101846409-8a19b200-3b59-11eb-8279-e0210689c47d.png)

**Comment by TarekRaafat** [comment] 2020-12-11 14:15
Hello @sellsteam13,

I've checked the [link](http://tsymbal01.beget.tech/dev/recomed/dist/page-main.html) you've shared and tried the search term you've specified `google.com` and it worked for me as shown in the below picture isn't that the expected behavior?

<img width="1428" alt="Screen Shot 2020-12-11 at 4 13 49 PM" src="https://user-images.githubusercontent.com/3501930/101913686-f9c88500-3bcb-11eb-9dfd-a387c6736c34.png">

**Comment by sellsteam13** [comment] 2020-12-12 09:14
Hi, @TarekRaafat !
It doesn't work on MacOS High Sierra. (Chrome v87, Safari 13.1.2, FireFox 83.0).  
I think on Windows everything is ok.
If u have any idea how i can fix it on Mac, please let me know :)

**Comment by TarekRaafat** [comment] 2020-12-12 10:04
Hello @sellsteam13,

I'm glad it works fine on windows because unfortunately I don't have one to try it on.

I've tried it on my Mac Big Sur, Linux Ubuntu latest version, and Chrome OS latest version and it works perfectly fine on the three Operating Systems as expected.

Please share your autoComplete.js setup if possible or anything that might help me debugging.


Have nice day, cheers! :)

**Comment by sellsteam13** [comment] 2020-12-12 10:20
@TarekRaafat 
![Снимок экрана 2020-12-12 в 12 18 32](https://user-images.githubusercontent.com/60786111/101981283-626b3c80-3c74-11eb-9149-9c932b4cc03e.png)

**Comment by sellsteam13** [comment] 2020-12-12 10:53
@TarekRaafat It's just magic. It started working. Thank you for your time. Have a good weekend !

**Comment by TarekRaafat** [comment] 2020-12-12 18:08
@sellsteam13 is there anything you had to do to get it to work?

**Comment by TarekRaafat** [comment] 2020-12-12 18:10
@lougroshek please try [v8.1](https://github.com/TarekRaafat/autoComplete.js/releases/tag/v8.1.0) and let me know if it resolved your issue or not.

**Comment by sellsteam13** [comment] 2020-12-12 18:16
@TarekRaafat good evening. 
Nothing, It started to work by itself.

**Comment by TarekRaafat** [comment] 2020-12-12 18:20
@sellsteam13 thanks for your prompt feedback really appreciate it! :)

I believe it should be fixed by now in [v8.1](https://github.com/TarekRaafat/autoComplete.js/releases/tag/v8.1.0)

**Comment by lougroshek** [comment] 2020-12-14 16:51
@TarekRaafat Works!! Thank you for the quick response!

**Comment by TarekRaafat** [comment] 2020-12-14 16:57
@lougroshek awesome! I'm glad that everything is working smoothly with you.

Please let me know if you need any support.


Have a nice day guys, cheers! :)

**Closed by TarekRaafat** 2020-12-14 16:57 UTC
Labels: bug
